name: ci

on:
  push:
    branches: [ master, 'develop' ]
  pull_request:
    branches: [ master, 'develop' ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run FancyGradient unit tests
      run: xcodebuild -scheme FancyGradient test -destination "platform=iOS Simulator,name=iPhone 12 mini"

